### ISSUE TITLE
update birthday

### ISSUE THREAD

**Issue by hikko624** [hikko624/rubiderella#24]
現状`birthday`の値が`6/24`のように`String`として保存されている
これを`Name`のように以下のようにする
```yaml
birthday:
  month: 6
  day: 24
```
